// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['views']['AccountsView']['AddAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['views']['AccountsView']['GetAccounts']();
}

export function GetSelectedAccount() {
  return window['go']['views']['AccountsView']['GetSelectedAccount']();
}

export function RemoveAccount(arg1) {
  return window['go']['views']['AccountsView']['RemoveAccount'](arg1);
}

export function SelectOneAccount(arg1) {
  return window['go']['views']['AccountsView']['SelectOneAccount'](arg1);
}
