// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {views} from '../models';

export function AddAccount(arg1:views.AddAccountReq):Promise<views.AddAccountResp>;

export function GetAccounts():Promise<views.GetAccountsResp>;

export function GetSelectedAccount():Promise<views.GetSelectedAccountResp>;

export function RemoveAccount(arg1:number):Promise<views.GetAccountsResp>;

export function SelectOneAccount(arg1:number):Promise<views.SelectOneAccountResp>;
