// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHome() {
  return window['go']['views']['HomeView']['GetHome']();
}

export function SaveHome(arg1) {
  return window['go']['views']['HomeView']['SaveHome'](arg1);
}

export function SetRunning(arg1) {
  return window['go']['views']['HomeView']['SetRunning'](arg1);
}
