// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {views} from '../models';

export function GetHome():Promise<views.GetHomeResp>;

export function SaveHome(arg1:views.GetHomeRespData):Promise<views.GetHomeResp>;

export function SetRunning(arg1:boolean):Promise<views.GetHomeResp>;
