name: Test Wails Build

on:
  push:
    branches: [release/*, main, bugfix/*]
  workflow_dispatch:

jobs:
  test_go:
    name: Run Go Tests
    if: github.repository == 'MasonStore/RobotForTelegram'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-11]
        go-version: ['1.21.7']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: ./app/go.sum

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run tests (mac)
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-11'
        env:
          CGO_LDFLAGS: -framework UniformTypeIdentifiers -mmacosx-version-min=10.13
        working-directory: ./app
        run: |
          go install github.com/wailsapp/wails/cmd/wails@latest
          go test -v ./...
          wails build

      - name: Run tests (!mac)
        if: matrix.os != 'macos-latest' && matrix.os != 'macos-11'
        working-directory: ./app
        run: |
          go install github.com/wailsapp/wails/cmd/wails@latest
          go test -v ./...
          wails build
